changelog:
  categories:
    - title: Change
      labels:
        - enhancement
        - feature
        - change
        - feat
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
        - docs
        - documentation
        - refactor
        - test
    - title: Other Changes
      labels:
        - "*"
